export const AUTH_MICROSERVICE = 'AUTH_SERVICE';
export const COMMITMENTS_MICROSERVICE = 'COMMITMENTS_SERVICE';
export const LISTINGS_MICROSERVICE = 'LISTINGS_SERVICE';
export const NOTIFICATIONS_MICROSERVICE = 'NOTIFICATIONS_SERVICE';
export const ORDERS_MICROSERVICE = 'ORDERS_SERVICE';
export const PAYMENTS_MICROSERVICE = 'PAYMENTS_SERVICE';
export const USERS_MICROSERVICE = 'USERS_SERVICE';